// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Blog struct {
	ID        pgtype.UUID        `json:"id"`
	Author    pgtype.UUID        `json:"author"`
	Title     string             `json:"title"`
	Body      string             `json:"body"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

type Follow struct {
	ID        pgtype.UUID        `json:"id"`
	Follower  pgtype.UUID        `json:"follower"`
	Followee  pgtype.UUID        `json:"followee"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}

type User struct {
	ID        pgtype.UUID        `json:"id"`
	UserName  string             `json:"username"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}
